spring.application.name=URL_Shortner


#applicationconfig
spring.config.import=optional:file:.env[.properties]


#mysql configaration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


#hibernate config
spring.jpa.show-sql=true
spring.jpa.generate-ddl=false
spring.jpa.hibernate.ddl-auto=none
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


#flyway config
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


#server config
server.port=8081
server.servlet.context-path=/api


#redis config
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}


#API config
thread.feed.api.key=${API_KEY}
springdoc.swagger-ui.enabled=true


#app config
app.domain=http://shortly.com


##spring security
spring.security.user.name=admin
spring.security.user.password=mypassword
Jwt.secretKey=${JWT_SECRET}


#logger config
logging.level.com.URI.URL_Shortner=DEBUG
#logging.level.org.springframework.web=INFO
#logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%level] [%thread] %logger{36} - %msg%n


#email configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
