CREATE TABLE USERS (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    username VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    MobileNo VARCHAR(20) NOT NULL,

    CONSTRAINT PK_USERS PRIMARY KEY (ID),
    CONSTRAINT UK_USERS_USERNAME UNIQUE (username),
    CONSTRAINT UK_USERS_EMAIL UNIQUE (Email),
    CONSTRAINT UK_USERS_MOBILENO UNIQUE (MobileNo)
);