CREATE TABLE users (
    id BIGINT NOT NULL AUTO_INCREMENT,
    user_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    mobile_no VARCHAR(20) NOT NULL,

    CONSTRAINT PK_USERS PRIMARY KEY (id),
    CONSTRAINT UK_USERS_USERNAME UNIQUE (user_name),
    CONSTRAINT UK_USERS_EMAIL UNIQUE (email),
    CONSTRAINT UK_USERS_MOBILENO UNIQUE (mobile_no)
);